services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  
  app:
    image: openjdk:21-jdk-slim
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/target
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    command: >
      sh -c "apt-get update && \
              apt-get install -y maven git && \
              apt-get clean && \
              cd /app && \
              mvn dependency:go-offline && \
              mvn spring-boot:run"
